### ISSUE TITLE
As a team member, I want to join my team’s deck, so that I can see other cards

### ISSUE THREAD

**Issue by kdduan** [software-students-fall2021/project-setup-penguin#17] opened 2021-10-17 18:57 UTC
## Estimation of work
- TBD

## Acceptance criteria
- [ ] foo
- [ ] bar
- [ ] baz
- [ ] etc

**Comment by janethuangg** [comment] 2021-10-17 21:18
duplicate of https://github.com/software-students-fall2021/project-setup-penguin/issues/19 and https://github.com/software-students-fall2021/project-setup-penguin/issues/18

**Closed by janethuangg** 2021-10-17 21:18 UTC
Labels: user story
